export default [
    {
        id:1,
        img:'https://raw.githubusercontent.com/SilvaLucas92/portfolio-LucasSilva/master/public/images/Javascript_Logo.png',
        name:'JavaScript'
    },
    {
        id:2,
        img:'https://raw.githubusercontent.com/SilvaLucas92/portfolio-LucasSilva/master/public/images/html2.png',
        name:'HTML'
    },
    {
        id:3,
        img:'https://raw.githubusercontent.com/SilvaLucas92/portfolio-LucasSilva/master/public/images/aa.webp',
        name:'CSS'
    },
    {
        id:4,
        img:'https://raw.githubusercontent.com/SilvaLucas92/portfolio-LucasSilva/master/public/images/my1.png',
        name:'MySQL'
    },
    {
        id:5,
        img:'https://raw.githubusercontent.com/SilvaLucas92/portfolio-LucasSilva/master/public/images/atom.png',
        name:'ReactJS'
    },
    {
        id:6,
        img:'https://raw.githubusercontent.com/SilvaLucas92/portfolio-LucasSilva/master/public/images/descarga.png',
        name:'NodeJS'
    },

]